### ISSUE TITLE
Brute forcing Buttercup

### ISSUE THREAD

**Issue by perry-mitchell** [fkasler/butterbrute#1]
Hey this is awesome - So weird to see any library dedicated to cracking Buttercup vaults.. feels kind of meta :) 

Would you have any results in terms of how efficiently Buttercup vaults were to dissect and brute force? We're looking for ways to improve our encryption setup, and will soon hopefully switch out the key derivation for argon2 or something similar. It'd be great to hear your opinion on the subject!

Anyway, thanks for sharing this!

**Comment by fkasler** [comment]
So glad you like it @perry-mitchell :) I had fun diving into the crypto, and would be more than happy to discuss ways to make it better. In short, the key to discouraging brute forces attacks is to make it painful! By that, I mean end users will not complain if takes them up to even a few seconds to unlock the vault. But for hackers, a few seconds per attempt would be egregiously slow and greatly reduce the feasibility of a dictionary attack.

**Comment by perry-mitchell** [comment]
Agreed, and this is the direction we want to head in. Might I ask where you think our time would best be spent? In terms of complicating our crypto..

Does argon2 sound like a good replacement for pbkdf2 to you? Imo it's likely to be far better a replacement, especially as it's tune-able in terms of resources rather than just arbitrary iterations.

**Comment by fkasler** [comment]
Hey @perry-mitchell, I would prefer to avoid the idea of complicating the crypto, and instead propose a simple solution that is also just very expensive timewise. Argon2 is an interesting idea, but it looks like there have already been some demonstrated attacks against it that basically implement the hashing logic more efficiently to weaken its intended security features. Those issues have supposedly been fixed, but I'm sure there will be more research in the future. Keep in mind that by increasing iterations on any key derivation function, you are indirectly increasing the resources required to crack the password.

I'd be happy to chat more about Buttercup security, but maybe it would be best to just set up a call? Go check your Twitter DMs ;)
